/**
 * @file The <code>extension</code> module serves to encapsulate the class of
 * the same name. The <code>Extension</code> class serves as a largely content-
 * free superclass that is extended by subsequent subclasses representing
 * specific extensions/plugins that are run in tandem by the bot. The class
 * shares certain similarities with the [Command]{@link module:command~Command}
 * superclass.
 * @module extension
 * @author Andrew Eissen <andrew@andreweissen.com>
 */
"use strict";

/**
 * @classdesc The <code>Extension</code> class serves as a framework class whose
 * primary purpose is to permit extension (no pun intended) by more specific
 * extension subclasses. The two most important methods are the unimplemented
 * [Extension#onMessage]{@link module:extension~Extension#onMessage} and the
 * implemented [Extension#addReply]{@link module:extension~Extension#addReply}.
 * The former serves as the extension's event listener callback function that is
 * invoked on "message" events generated by the inclusion of a new message in
 * one of the server's channels. The latter method serves to interface with the
 * server's channels by posting responses to user posts, replies that can either
 * remove themselves after a set interval if needed or remain logged.
 * <br />
 * <br />
 * The other methods and members belonging to the <code>Extension</code> class
 * constitute the various private properties and their individual setter and
 * getter methods. Other extending classes may implement their own private
 * prototype methods as needed, but <code>Extension</code> exists solely for
 * subsequent subclass extension and thus lacks its own dedicated functionality.
 * @class
 */
class Extension {

  /**
   * @description The <code>Extension</code> constructor is used simply to store
   * the <code>string</code>, <code>boolean</code>, and <code>Object</code>
   * parameter properties passed during the class's initial initialization
   * (via [loadExtensionDir]{@link module:client~Client#loadExtensionDir}) in
   * private fields via dedicated setters that ensure parameters are of the
   * correct data type.
   * @constructor
   * @param {string} name - Individual name of the extension ("commander",
   * "logger" etc.)
   * @param {boolean} loaded - Flag denoting the extension's loaded or unloaded
   * status, depending on whether a class instance already exists in the
   * <code>Client</code> instance's <code>Discord.Collection</code> map, namely
   * [Client#extensions]{@link module:client~Client#extensions}.
   * @param {Object} config - A reference to the instantiating
   * <code>Client</code> class instance's own [Client#config]{@link
   * module:client~Client#config} <code>Object</code>, containing all the custom
   * configuration options available for tweaking prior to installation.
   * @param {Object} lang - A reference to a subclass-specific nested
   * <code>Object</code> constituting a property of the instantiating
   * <code>Client</code> class instance's own
   * [lang]{@link module:client~Client#lang} <code>Object</code>, containing
   * messages specific to the subclass being instantiated rather than a
   * reference to the whole <code>Client#lang</code> <code>Object</code>.
   */
  constructor (name, loaded, config, lang) {

    /**
     * @description The <code>name</code> <code>string</code> property is a
     * private internal field representing the name of the specific extension
     * or plugin being initialized.
     * @member {string}
     */
    this.name = name;

    /**
     * @description The <code>loaded</code> <code>boolean</code> property is a
     * private internal field denoting whether a class instance of its type
     * exists in the <code>Client</code> instance's [Discord.Collection]{@link
     * https://discord.js.org/#/docs/collection/master/class/Collection}
     * property, [extensions]{@link module:client~Client#extensions}.
     * @member {boolean}
     */
    this.loaded = loaded;

    /**
     * @description The <code>config</code> <code>Object</code> property is a
     * reference to the instantiating <code>Client</code> class instance's own
     * [config]{@link module:client~Client#config} <code>Object</code>, the
     * container for all the custom configuration options available for tweaking
     * prior to installation of the application.
     * @member {Object}
     * @see [Client#config]{@link module:client~Client#config}
     */
    this.config = config;

    /**
     * @description The <code>lang</code> <code>Object</code> property is a
     * reference to a subclass-specific nested <code>Object</code> constituting
     * a property of the instantiating <code>Client</code> class instance's own
     * [lang]{@link module:client~Client#lang} <code>Object</code>. This
     * <code>Object</code>'s contents include messages specific to the subclass
     * being instantiated rather than a reference to the whole
     * <code>Client#lang</code> <code>Object</code>.
     * @member {Object}
     * @see [Client#lang]{@link module:client~Client#lang}
     */
    this.lang = lang;
  }

  /**
   * @description <code>set name</code> serves as the setter method for the
   * <code>name</code> parameter property representing the extension's name. It
   * checks to ensure that the parameter <code>name</code> is of the primitive
   * <code>string</code> type or the <code>String</code> wrapper
   * <code>Object</code>, applying an empty string to the internal field if
   * the parameter is not of the proper type.
   * @function
   * @param {string|String} name - The parameter to be assigned as the internal
   * <code>_name</code>. It should be a primitive <code>string</code> or an
   * <code>Object</code> of the <code>String</code> wrapper class.
   * @returns {void}
   */
  set name (name) {
    this._name = typeof name === "string" || name instanceof String ? name : "";
  }

  /**
   * @description <code>set loaded</code> serves as the setter method for the
   * <code>loaded</code> parameter property representing whether the greater
   * application has already instantiated a member of the class and added it to
   * the <code>Client</code> class instance's [Discord.Collection]{@link
   * https://discord.js.org/#/docs/collection/master/class/Collection} property,
   * [extensions]{@link module:client~Client#extensions}.
   * It checks to ensure that the parameter <code>loaded</code> is of the
   * primitive <code>boolean</code> type, applying a default value of
   * <code>false</code> to the internal field if the parameter is not of the
   * proper type.
   * @function
   * @param {boolean} loaded - The parameter to be assigned as the internal
   * <code>_loaded</code>. It should be a primitive <code>boolean</code>.
   * @returns {void}
   */
  set loaded (loaded) {
    this._loaded = typeof loaded === "boolean" ? loaded : false;
  }

  /**
   * @description <code>set config</code> serves as the setter method for the
   * <code>config</code> parameter property representing the a reference to the
   * instantiating <code>Client</code> class instance's own
   * [config]{@link module:client~Client#config} <code>Object</code>, the
   * container for all the custom configuration options available for tweaking
   * prior to installation of the application. It checks to ensure that the
   * parameter <code>config</code> is of the <code>Object</code> type, applying
   * a default empty <code>Object</code> to the internal field if the parameter
   * is not of the proper type.
   * @function
   * @param {Object} config - The parameter to be assigned as the internal
   * <code>_config</code>. It should be an <code>Object</code>.
   * @returns {void}
   */
  set config (config) {
    this._config = typeof config === "object" && config.constructor === Object
      ? config
      : {};
  }

  /**
   * @description <code>set lang</code> serves as the setter method for the
   * <code>lang</code> parameter property representing the a reference to the
   * instantiating <code>Client</code> class instance's own
   * [lang]{@link module:client~Client#lang} <code>Object</code> containing
   * messages specific to the subclass being instantiated. It checks to ensure
   * that the parameter <code>config</code> is of the <code>Object</code> type,
   * applying a default empty <code>Object</code> to the internal field if the
   * parameter is not of the proper type.
   * @function
   * @param {Object} lang - The parameter to be assigned as the internal
   * <code>_lang</code>. It should be an <code>Object</code>.
   * @returns {void}
   */
  set lang (lang) {
    this._lang = typeof lang === "object" && lang.constructor === Object
      ? lang
      : {};
  }

  /**
   * @description <code>get name</code> serves as the getter method for the
   * <code>name</code> property. It simply returns the value of the internal
   * field, be that the parameter value passed to the constructor during
   * initialization or the default empty <code>string</code> value.
   * @function
   * @returns {string} _name - Value of the internal <code>string</code>
   */
  get name () {
    return this._name;
  }

  /**
   * @description <code>get loaded</code> serves as the getter method for the
   * <code>loaded</code> property. It simply returns the value of the internal
   * field, be that the parameter value passed to the constructor during
   * initialization or the default <code>false</code> value.
   * @function
   * @returns {boolean} _loaded - Value of the internal <code>boolean</code>
   */
  get loaded () {
    return this._loaded;
  }

  /**
   * @description <code>get config</code> serves as the getter method for the
   * <code>config</code> property. It simply returns the value of the internal
   * field, be that the parameter value passed to the constructor during
   * initialization or the default empty <code>Object</code>.
   * @function
   * @returns {Object} _config - Value of the internal <code>Object</code>
   */
  get config () {
    return this._config;
  }

  /**
   * @description <code>get lang</code> serves as the getter method for the
   * <code>lang</code> property. It simply returns the value of the internal
   * field, be that the parameter value passed to the constructor during
   * initialization or the default empty <code>Object</code>.
   * @function
   * @returns {Object} _lang - Value of the internal <code>Object</code>
   */
  get lang () {
    return this._lang;
  }

  /**
   * @description The <code>addReply</code> method is used to log a new reply
   * directed at the user invoking the given command that provides information
   * about the state of the request. The method can remove the user's post and
   * the bot reply after a set interval if needed, or can leave both posts in
   * the channel for subsequent viewing. The former is generally used in the
   * context of verification requests to ensure that the verify channel doesn't
   * get cluttered, while the latter is more useful in "about" requests that
   * display information about a given user on request.
   * <br />
   * <br />
   * Originally, in the days when the <code>Droid</code> application's main
   * functionality was restricted to command invocations, this method belonged
   * to the <code>Client</code> class, and a copy of this function bound to that
   * class instance was passed to each command subclasses's [execute]{@link
   * module:command~Command#execute} method to ensure that the
   * <code>Client</code> class was the only module to interact with the server
   * channels. Subclasses extending [Command]{@link module:command~Command} were
   * only to contain application logic related to those commands, leaving the
   * posting of results to this method.
   * <br />
   * <br />
   * However, with the subsequent expansion of the application to include more
   * functionality (in the form of plugins/extensions) than commands alone, the
   * method was moved to the <code>Extension</code> superclass and passed along
   * to each new extension subclass for ease of logging results in the server.
   * The <code>Client</code> class no longer exclusively handles posting results
   * to the server channels, and solely focuses on logging in and loading all
   * extensions.
   * @function
   * @param {Object} message - A new [Discord.Message]{@link
   * http://discord.js.org/#/docs/main/master/class/Message} class instance
   * containing information pertaining to the most recent server message, its
   * author, and the channel in which it was posted, among other data.
   * @param {string} langMessage - The text of the specific message to log,
   * generally a relevant property of [lang]{@link module:client~Client#lang}.
   * @param {boolean} [deleteMessages=true] - A <code>boolean</code> flag
   * denoting whether to delete the poster's original message and the bot's
   * reply after the interval defined in [config]{@link
   * module:client~Client#config} has elapsed. This optional field is set to
   * <code>true</code> by default.
   * @returns {void}
   */
  addReply (message, langMessage, deleteMessages = true) {
    if (deleteMessages) {
      message.delete();
    }

    // Direct reponse to the user directly
    message.reply(langMessage).then(msg => {
      if (deleteMessages) {
        msg.delete({
          timeout: this.config.utility.interval
        });
      }
    }).catch(console.error);
  }

  /**
   * @description The <code>onMessage</code> event listener callback function is
   * left unimplemented by default in the <code>Extension</code> superclass,
   * with the expectation that extending subclasses will be the ones to
   * implement this function. It is the most important method of the respective
   * classes, as it is the method that serves as the callback function when new
   * "message" events are triggered by a user posting a reply in a server
   * channel.
   * @function
   * @param {Object} message - A new [Discord.Message]{@link
   * http://discord.js.org/#/docs/main/master/class/Message} class instance
   * containing information pertaining to the most recent server message, its
   * author, and the channel in which it was posted, among other data.
   * @returns {void}
   */
  onMessage (message) {}
}

module.exports = Extension;